services:
    frontend:
      container_name: "ebookpresenter-js.frontend"
      image: "ebookpresenter-js.frontend"
      ports:
          - 3001:4321
      build:
          dockerfile: frontend.dockerfile
    api:
        container_name: "ebookpresenter-js.api"
        image: "ebookpresenter-js.api"
        ports:
            - 3000:3000
        build: 
            dockerfile: backend.dockerfile
        volumes:
          - /home/jesper/Dropbox/Ebook/:/books/
